version: '3'

services:
  iot-client-dev:
    image: iot-client-dev
    build: ./iot-client
    container_name: iot-container-dev
    restart: always
    ports:
      - "5000:5000"
    environment:
      - EVENTHUB_CONNECTION_STRING=Endpoint=sb://iothub-ns-my-iot-hub-64462241-269f6eda4d.servicebus.windows.net/;SharedAccessKeyName=service;SharedAccessKey=MkA4ElETbP6L7qBEvtR3ugiC5BXHpw3M+AIoTCUSARM=;EntityPath=my-iot-hub-456
      - CONSUMER_GROUP=$Default
      - DEVICE_ID=48:CA:43:36:71:04
      - API_KEY=Xj7Bq9Lp2Rt5Zk8Mn3Vx6Hs1
      - USE_MOCK_DATA=false
      - DATA_STALENESS_TIMEOUT=300
      - FLASK_ENV=development
    networks:
      - app-network

  nginx:
    image: nginx:latest
    container_name: nginx-proxy
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./iot-client/nginx/conf.d:/etc/nginx/conf.d
      - ./iot-client/nginx/ssl:/etc/nginx/ssl
      - ./iot-client/nginx/www:/var/www/html
    depends_on:
      - iot-client-dev
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
